org.gradle.jvmargs = -Xmx3G
org.gradle.java.home = C:/Program Files/Java/jdk-21.0.10
org.gradle.daemon = false
org.gradle.parallel = false
org.gradle.caching = true

# Minecraft / NeoForge
minecraft_version = 1.21.1
neo_version = 21.1.219

# Create baseline
create_version = 6.0.11
registrate_version = MC1.21-1.3.0+67
ponder_version = 1.0.82
flywheel_version = 1.0.6
flywheel_version_range = [1.0.0,2.0)

# Mod info
mod_id = hyperpressure
mod_name = HyperPressure Engineering
mod_version = 0.1.0-alpha
mod_group_id = com.kaifa.hyperpressure
mod_authors = KAIFA6666
mod_license = ARR
mod_description = A Create addon about high-pressure fluids, compressed air, and controllable engineering risk.
